---
-   name: Install Docker SDK dependencies
    apt:
      name:
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: present
      update_cache: yes

-   name: Install Docker SDK for Python
    environment:
      PIP_BREAK_SYSTEM_PACKAGES: 1
    pip:
      name: docker
